from langgraph.prebuilt import create_react_agent

from .models import gpt_41, gpt_41_mini
from .utils import trim_history
from .tools import gather_data_tool, min_tool, max_tool, average_tool, sum_tool

data_agent = create_react_agent(
    model=gpt_41_mini,
    name="data_agent",
    pre_model_hook=trim_history,
    tools=[gather_data_tool],
    prompt="""
    You are a data gathering agent.
    Your task is to gather data based on the user's request.
    """
)

math_agent = create_react_agent(
    model=gpt_41_mini,
    name="math_agent",
    pre_model_hook=trim_history,
    tools=[min_tool, max_tool, average_tool, sum_tool],
    prompt="""
    You are a math agent.
    Your task is to perform calculations based on the data provided by the data_agent.
    You will receive data from the data_agent and you will perform calculations on it.

    You must use appropriate tools to perform the calculations.
    The following tools are available:
    - min_tool: Calculate the minimum value from a list of dictionaries.
    - max_tool: Calculate the maximum value from a list of dictionaries.
    - average_tool: Calculate the average value from a list of dictionaries.
    - sum_tool: Calculate the sum of values from a list of dictionaries.
    You will return the result of the calculations.
    """
)

verification_agent = create_react_agent(
    model=gpt_41_mini,
    name="verification_agent",
    pre_model_hook=trim_history,
    tools=[],
    prompt="""
    You are a verification agent.
    Your task is to verify the report generated by the supervisor.
    You will receive a report and the data used to generate it.
    If the report is correct, you will respond with "Report verified".
    If the report is incorrect, you will respond with "Report not verified" and provide the reason.
    """
)
